name: lab2
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.0
#  firebase_messaging: ^14.9.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  url_launcher: ^6.1.10
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
